### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by darrenleeweber** [mapbox/mapbox-tile-copy#133]
```
$ nodejs --version
v10.15.1
$ npm --version
6.4.1
$ gdalinfo --version
GDAL 2.2.3, released 2017/11/20
$ apt-cache show libgdal-dev
Package: libgdal-dev
Architecture: amd64
Version: 2.2.3+dfsg-2

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

```
$ sudo npm install -g @mapbox/mapbox-tile-copy
[sudo] password for ubuntu: 
npm WARN deprecated tile-stat-stream@1.1.0: Package abandoned, contact support@npmjs.com for more info.
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated tiletype@0.2.1: This module is now under the @mapbox namespace: install @mapbox/tiletype instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
/usr/bin/mapbox-tile-copy -> /usr/lib/node_modules/@mapbox/mapbox-tile-copy/bin/mapbox-tile-copy.js

> gdal@0.9.8 install /usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for gdal@0.9.8 and node@10.15.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ubuntu/.node-gyp/10.15.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/.node-gyp'
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64/gdal.node" "--module_name=gdal" "--module_path=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64/gdal.node --module_name=gdal --module_path=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-45-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64/gdal.node --module_name=gdal --module_path=/usr/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/gdal/lib/binding/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdal@0.9.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdal@0.9.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-02-03T05_19_38_469Z-debug.log
```

**Comment by stevage** [comment]
Those issues aren't specific to this library. Generally, you don't want to install npm modules with `sudo`. I find the best solution is to `chmod myusername -R /usr/lib/node_modules`.
