### ISSUE TITLE
undefined symbol: napi_add_finalizer

### ISSUE THREAD

**Issue by rogsmith** [mapbox/mapbox-tile-copy#152]
I am trying to run mapbox-tile-copy, but receiving the following error:

module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/ubuntu/.nvm/versions/node/v8.15.1/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: napi_add_finalizer
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.15.1/lib/node_modules/@mapbox/mapbox-tile-copy/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

**Comment by NH-RedAnt** [comment]
I had this error after switching to  "nvm use v9.3.0" and attempting to "npm install" the current repo (Mon Oct 23 12:24:52 2023 +0200). 

I was able to get past this with "nvm use v19.3.0".  This may be the current version.

The REDME.md file contains an extra period after the v that "v.9.3.0" seems like it should be "nvm use v9.3.0", or maybe even "nvm use v19.3.0".

I'm also not getting a "kosmtik" command, nor anything like  "node_modules/kosmtik".  I do seem to be able to run "kosmtik" from the folder I "nmp instlled" in using "./index.js".
